stages:
  - test

test:
  stage: test
  image: node:latest
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  services:
    - selenium/standalone-chrome:latest
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install -g npm@latest
    - npm install -g typescript@latest
    - npm install
  script:
    - npm test
  artifacts:
    paths:
      - allure-report/
  tags:
    - shared-windows
    