
stages:
  - test

before_script:
  - npm install -g npm@latest
  - npm install -g typescript@latest
test:
  stage: test
  image: node:latest
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  services:
    - selenium/standalone-chrome:latest

  before_script:
    - npm install
  script:
    - npm test
  artifacts:
    paths:
      - allure-report/
  tags:
    - shared-windows
    